name: jogging
description: This pedometer uses the built-in sensor to count your steps. No GPS tracking, so it can greatly save battery.

publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  firebase_core: ^2.10.0
  auto_route: ^6.3.0
  connectivity_plus: ^3.0.5
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  shared_preferences: ^2.1.0
  state_notifier: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  http_mock_adapter: ^0.4.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  state_notifier_test: ^0.0.9
  test_coverage_badge: ^0.2.0

flutter:

  uses-material-design: true
