name: jogging
description: This pedometer uses the built-in sensor to count your steps. No GPS tracking, so it can greatly save battery.

publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  auto_route: ^6.4.0
  connectivity_plus: ^3.0.6
  adaptive_theme: ^3.2.0
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  shared_preferences: ^2.1.0
  riverpod_annotation: ^2.1.1
  cached_network_image: 3.2.3
  flutter_svg: ^2.0.5
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  custom_lint: 0.3.4
  riverpod_lint: ^1.3.1
  riverpod_generator: ^2.2.1
  auto_route_generator: ^6.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
