name: jogging
description: This pedometer uses the built-in sensor to count your steps. No GPS tracking, so it can greatly save battery.

publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter Localization for multiple languages
  flutter_localizations:
    sdk: flutter
  # Internationalization
  intl: ^0.17.0
  # Icons
  cupertino_icons: ^1.0.5
  # Navigator 2.0
  auto_route: ^6.4.0
  # To Check Internet Connectivity
  connectivity_plus: ^3.0.6
  # To implement dynamic theming
  adaptive_theme: ^3.2.0
  # For functional programming
  dartz: ^0.10.1
  # For internet requests
  dio: ^5.1.1
  # For hashcode mapping
  equatable: ^2.0.5
  # For State Management
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  # For generating freezed classes
  freezed_annotation: ^2.2.0
  # For storing key-values
  shared_preferences: ^2.1.0
  # For network image caching
  cached_network_image: 3.2.3
  # To load SVGs
  flutter_svg: ^2.0.5
  # Firebase
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  # To implement Google Sign in
  google_sign_in: ^6.1.0
  # To check the internet connection
  internet_connection_checker: ^1.0.0+1
  # To connect to Health Connect (Android) and HealthKit (iOS)
  health: ^6.0.0
  # Permission handler
  permission_handler: ^10.2.0
  # To draw charts
  fl_chart: ^0.62.0
  # To draw percent indicators
  percent_indicator: ^4.2.3
  # To create custom calendar
  syncfusion_flutter_calendar: ^21.1.41
  syncfusion_flutter_core: ^21.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  # To build generative classes
  build_runner: ^2.3.3
  # For flutter lints
  flutter_lints: ^2.0.1
  # To generate DTOs
  freezed: ^2.3.2
  # To create custom rules
  custom_lint: 0.3.4
  # For riverpod best practices
  riverpod_lint: ^1.3.1
  # To generate RiverPod providers
  riverpod_generator: ^2.2.1
  # To generate router config
  auto_route_generator: ^6.2.0
  # To generate app icon
  flutter_launcher_icons: 0.13.1

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  remove_alpha_ios: true
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/images/app-icon-background.png"
  adaptive_icon_foreground: "assets/images/app-icon-foreground.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Ultralight.otf
          weight: 100

